CREATE TABLE IF NOT EXISTS dice_rolls
(
    dice_roll_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dice_roll_request   VARCHAR,
    dice_roll_result    VARCHAR,
    dice_roll_timestamp TIMESTAMP WITHOUT TIME ZONE
);